"""Machine-readable runtime constants shared across transcription stages."""

from __future__ import annotations

RUNTIME_VERSION = "2"
STATE_SCHEMA_VERSION = 1
OUTPUT_SCHEMA_VERSION = 1
RUNTIME_ROOT_NAME = "meeting-transcriber"
VENV_DIRECTORY_NAME = ".venv"
VENV_STAMP_FILENAME = ".meeting-transcriber-runtime.json"

REPROBE_FLAG = "--reprobe"
RUNTIME_BOOTSTRAPPED_ENV = "TRANSCRIBING_AUDIO_RUNTIME_BOOTSTRAPPED"
RUNTIME_RECOVERY_ATTEMPT_ENV = "TRANSCRIBING_AUDIO_RUNTIME_RECOVERY_ATTEMPT"

DEFAULT_LOCAL_MODEL = "large-v3-turbo"
DEFAULT_ENGLISH_LOCAL_MODEL = "distil-large-v3"
DEFAULT_GIGAAM_MODEL = "v3_e2e_rnnt"
DEFAULT_GIGAAM_MAX_CHUNK_DURATION_S = 24.0
DEFAULT_OPENAI_MODEL = "whisper-1"
DEFAULT_DIARIZATION_MODEL = "FluidAudio/Community-1-CoreML"
DEFAULT_DIARIZATION_REVISION = "6428e29186573c6d33c598e25d460e6690bc0ee1"
DEFAULT_MAX_UPLOAD_BYTES = 24_000_000
DEFAULT_MAX_CHUNK_DURATION_S = 600.0
DEFAULT_OVERLAP_S = 2.0
DEFAULT_QUALITY_POLICY_VERSION = "2"

OUTPUT_JSON_SUFFIX = ".transcript.json"
OUTPUT_TEXT_SUFFIX = ".transcript.txt"
OUTPUT_SRT_SUFFIX = ".transcript.srt"
OUTPUT_VTT_SUFFIX = ".transcript.vtt"
